# Generated by Django 6.0 on 2026-03-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamoraapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
